build: cope with missing struct utmpx.ut_session
Cygwin has no utmpx.ut_session.

	utmp_register.c: In function "main2":
	utmp_register.c:172:7: error: "struct utmpx" has no member
	named "ut_session"
	  entry.ut_session = Opt.sess;
	       ^