build: build xcp without splice if not available
Cygwin does not have splice(2).

	xcp.c: In function "xcp_splice":
	xcp.c:76:3: warning: implicit declaration of function "splice"
	[-Wimplicit-function-declaration]
	   ret = splice(ifd, &ioff, pfd[1], NULL, isb.st_size, 0);
	   ^